------------------------------------------------
--                [EXTENSIONS]                --
------------------------------------------------
CREATE EXTENSION IF NOT EXISTS CITEXT;
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS tablefunc;
CREATE EXTENSION IF NOT EXISTS "pgcrypto";


------------------------------------------------
--                   [ENUMS]                  --
------------------------------------------------
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'author_role_enum') THEN
        CREATE TYPE author_role_enum AS ENUM ('Author', 'Artist');
    END IF;
END$$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'bug_type_enum') THEN
        CREATE TYPE bug_type_enum AS ENUM (
            'UI', 'Backend', 'Performance', 'Security', 'Database',
            'Network', 'Crash', 'Logic', 'Compatibility', 'Other'
        );
    END IF;
END$$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'manga_status_enum') THEN
        CREATE TYPE manga_status_enum AS ENUM (
            'Ongoing', 'Completed', 'Hiatus', 'Cancelled',
            'Discontinued', 'One-shot', 'Upcoming'
        );
    END IF;
END$$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'reading_status_enum') THEN
        CREATE TYPE reading_status_enum AS ENUM (
            'Reading', 'Completed', 'On Hold', 'Dropped',
            'Plan to Read', 'Rereading'
        );
    END IF;
END$$;


------------------------------------------------
--                  [SYSTEM]                  --
------------------------------------------------
CREATE TABLE IF NOT EXISTS app_infos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name CITEXT NOT NULL,
    value_str TEXT,
    value_int BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT app_infos_unique_cstr UNIQUE (name)
);


------------------------------------------------
--                   [MANGAS]                 --
------------------------------------------------
CREATE TABLE IF NOT EXISTS mangas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title CITEXT NOT NULL,
    descr TEXT,
    cover_image_url TEXT NOT NULL,
    status manga_status_enum NOT NULL,
    color TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mal_url TEXT,
    CONSTRAINT mangas_unique_title_cstr UNIQUE (title),
    CONSTRAINT mangas_descr_check CHECK (length(descr) <= 2048),
    CONSTRAINT mangas_title_check CHECK (length(title) <= 512)
);

CREATE TABLE IF NOT EXISTS manga_alt_titles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    manga_id BIGINT NOT NULL,
    title CITEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT manga_alt_titles_unique_alt_title UNIQUE (manga_id, title),
    FOREIGN KEY (manga_id) REFERENCES mangas(id) ON DELETE CASCADE ON UPDATE CASCADE
);


------------------------------------------------
--                   [AUTHORS]                --
------------------------------------------------
CREATE TABLE IF NOT EXISTS authors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT authors_author_unique_name_cstr UNIQUE (name)
);


CREATE TABLE IF NOT EXISTS manga_authors (
    author_id BIGINT NOT NULL,
    manga_id BIGINT NOT NULL,
    role author_role_enum NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (author_id, manga_id, role),
    FOREIGN KEY (author_id) REFERENCES authors(id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (manga_id) REFERENCES mangas(id) ON UPDATE CASCADE ON DELETE CASCADE

);


------------------------------------------------
--                   [GENRES]                 --
------------------------------------------------
CREATE TABLE IF NOT EXISTS genres (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre CITEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT genres_unique_genre_cstr UNIQUE (genre)
);

CREATE TABLE IF NOT EXISTS manga_genres (
    genre_id BIGINT NOT NULL,
    manga_id BIGINT NOT NULL,
    PRIMARY KEY (genre_id, manga_id),
    FOREIGN KEY (genre_id) REFERENCES genres(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (manga_id) REFERENCES mangas(id) ON DELETE CASCADE ON UPDATE CASCADE
);


------------------------------------------------
--               [CHAPTERS]                   --
------------------------------------------------
CREATE TABLE IF NOT EXISTS chapters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    manga_id BIGINT NOT NULL,
    chapter_index INT NOT NULL,
    chapter_name TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chapters_unique_chapter_cstr UNIQUE (manga_id, chapter_index),
    FOREIGN KEY (manga_id) REFERENCES mangas(id) ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE IF NOT EXISTS chapter_images (
    chapter_id BIGINT NOT NULL,
    image_index INT NOT NULL,
    image_url TEXT NOT NULL,
    width INT NOT NULL,
    height INT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (chapter_id, image_index),
    FOREIGN KEY (chapter_id) REFERENCES chapters(id) ON DELETE CASCADE ON UPDATE CASCADE
) PARTITION BY HASH (chapter_id);

-- partitions
CREATE TABLE IF NOT EXISTS chapter_images_p0 PARTITION OF chapter_images FOR VALUES WITH (MODULUS 10, REMAINDER 0);
CREATE TABLE IF NOT EXISTS chapter_images_p1 PARTITION OF chapter_images FOR VALUES WITH (MODULUS 10, REMAINDER 1);
CREATE TABLE IF NOT EXISTS chapter_images_p2 PARTITION OF chapter_images FOR VALUES WITH (MODULUS 10, REMAINDER 2);
CREATE TABLE IF NOT EXISTS chapter_images_p3 PARTITION OF chapter_images FOR VALUES WITH (MODULUS 10, REMAINDER 3);
CREATE TABLE IF NOT EXISTS chapter_images_p4 PARTITION OF chapter_images FOR VALUES WITH (MODULUS 10, REMAINDER 4);
CREATE TABLE IF NOT EXISTS chapter_images_p5 PARTITION OF chapter_images FOR VALUES WITH (MODULUS 10, REMAINDER 5);
CREATE TABLE IF NOT EXISTS chapter_images_p6 PARTITION OF chapter_images FOR VALUES WITH (MODULUS 10, REMAINDER 6);
CREATE TABLE IF NOT EXISTS chapter_images_p7 PARTITION OF chapter_images FOR VALUES WITH (MODULUS 10, REMAINDER 7);
CREATE TABLE IF NOT EXISTS chapter_images_p8 PARTITION OF chapter_images FOR VALUES WITH (MODULUS 10, REMAINDER 8);
CREATE TABLE IF NOT EXISTS chapter_images_p9 PARTITION OF chapter_images FOR VALUES WITH (MODULUS 10, REMAINDER 9);


------------------------------------------------
--                   [USERS]                  --
------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    username CITEXT NOT NULL,
    email CITEXT NOT NULL,
    p_hash BYTEA NOT NULL,
    perfil_image_url TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_login_at TIMESTAMPTZ,
    CONSTRAINT users_unique_username UNIQUE (username),
    CONSTRAINT users_unique_email UNIQUE (email),
    CONSTRAINT users_check_email CHECK (email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'),
    CONSTRAINT users_username_length CHECK ((length(username) <= 64))
);


CREATE TABLE IF NOT EXISTS user_session_tokens (
    refresh_token TEXT PRIMARY KEY,
    user_id UUID NOT NULL,
    issued_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at TIMESTAMPTZ NOT NULL,
    revoked BOOLEAN NOT NULL DEFAULT FALSE,
    revoked_at TIMESTAMPTZ,
    device_name TEXT NOT NULL,
    device_ip INET NOT NULL,
    user_agent TEXT NOT NULL,
    last_used_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT fk_user_session_user FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT user_session_tokens_unique_user_device UNIQUE (user_id, device_ip, user_agent),
    CONSTRAINT chk_expires_after_issued CHECK (expires_at > issued_at),
    CONSTRAINT chk_revoked_at_when_revoked CHECK ((revoked = FALSE AND revoked_at IS NULL) OR (revoked = TRUE AND revoked_at IS NOT NULL))
);


CREATE TABLE IF NOT EXISTS user_login_attempts (
    user_id UUID PRIMARY KEY,
    attempts INT NOT NULL DEFAULT 0,
    last_failed_login TIMESTAMPTZ,
    locked_until TIMESTAMPTZ,
    last_successful_login TIMESTAMPTZ,
    CONSTRAINT fk_login_attempts_user FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT chk_attempts_non_negative CHECK (attempts >= 0),
    CONSTRAINT chk_attempts_reasonable CHECK (attempts <= 1000)
);

------------------------------------------------
--              [USER INTERACTIONS]           --
------------------------------------------------
CREATE TABLE IF NOT EXISTS library (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    manga_id BIGINT NOT NULL,
    user_id UUID NOT NULL,
    reading_status reading_status_enum NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT library_unique_reading_status UNIQUE (manga_id, user_id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (manga_id) REFERENCES mangas(id) ON DELETE CASCADE ON UPDATE CASCADE
);


-- Coleções de mangas
CREATE TABLE IF NOT EXISTS collections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title CITEXT NOT NULL,
    descr TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT collections_unique_title UNIQUE (title),
    CONSTRAINT collections_title_cstr CHECK (length(title) < 64),
    CONSTRAINT collections_descr_cstr CHECK (length(descr) < 512)
);

-- Mangas pertencentes as coleções
CREATE TABLE IF NOT EXISTS collections_mangas (
    collection_id BIGINT NOT NULL,
    manga_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (collection_id, manga_id),
    FOREIGN KEY (collection_id) REFERENCES collections(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (manga_id) REFERENCES mangas(id) ON DELETE CASCADE ON UPDATE CASCADE
);

------------------------------------------------
--                 [REPORTS]                  --
------------------------------------------------
CREATE TABLE IF NOT EXISTS bug_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    descr TEXT,
    bug_type bug_type_enum NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT bug_reports_title_length CHECK (length(title) < 128),
    CONSTRAINT bug_reports_descr_length CHECK (length(descr) < 1024)
);


CREATE TABLE IF NOT EXISTS manga_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT manga_requests_title_length_cstr CHECK (length(title) <= 128),
    CONSTRAINT manga_requests_message_length_cstr CHECK (length(message) < 256)
);


CREATE TABLE IF NOT EXISTS manga_blacklist (
    manga_id BIGINT PRIMARY KEY,
    descr TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (manga_id) REFERENCES mangas(id)
);

------------------------------------------------
--                 [METRICS]                  --
------------------------------------------------
CREATE TABLE IF NOT EXISTS user_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    metric_date DATE NOT NULL DEFAULT CURRENT_DATE,
    total_logins INT DEFAULT 0,
    mangas_read INT DEFAULT 0,
    chapters_read INT DEFAULT 0,
    time_spent_seconds BIGINT DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT user_metrics_unique_cstr UNIQUE (user_id, metric_date),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE IF NOT EXISTS manga_metrics (
    manga_id BIGINT PRIMARY KEY NOT NULL,
    total_reads INT DEFAULT 0,
    total_chapters INT DEFAULT 0,
    total_collections INT DEFAULT 0,
    FOREIGN KEY (manga_id) REFERENCES mangas(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS chapter_metrics (
    chapter_id BIGINT PRIMARY KEY NOT NULL,
    total_views INT DEFAULT 0,
    FOREIGN KEY (chapter_id) REFERENCES chapters(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS global_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    metric_date DATE NOT NULL DEFAULT CURRENT_DATE,
    total_users BIGINT DEFAULT 0,
    active_users BIGINT DEFAULT 0,
    total_mangas BIGINT DEFAULT 0,
    total_chapters BIGINT DEFAULT 0,
    total_reads BIGINT DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT global_metrics_unique_cstr UNIQUE (metric_date)
);

------------------------------------------------
--                  [LOGS]                    --
------------------------------------------------

CREATE TABLE IF NOT EXISTS logs (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    level VARCHAR(50) NOT NULL,
    message TEXT NOT NULL,
    path TEXT,
    method VARCHAR(10),
    status_code INT,
    stacktrace TEXT,
    metadata JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    CONSTRAINT chk_log_level CHECK (level IN ('DEBUG', 'INFO', 'WARN', 'ERROR', 'FATAL'))
);


------------------------------------------------
--                 [VIEWS]                    --
------------------------------------------------
DROP MATERIALIZED VIEW manga_page_view CASCADE;
CREATE MATERIALIZED VIEW IF NOT EXISTS manga_page_view AS
SELECT
    m.id,
    m.title,
    m.descr,
    m.status,
    m.color,
    m.cover_image_url,
    m.mal_url,
    m.updated_at,
    m.created_at,

    COALESCE(
        (
            SELECT
                total_reads
            FROM
                manga_metrics
            WHERE
                manga_metrics.manga_id = m.id
        ),
        0::BIGINT
    ) as views,

    COALESCE(
        (
            SELECT json_agg(jsonb_build_object(
                'id', c.id,
                'chapter_name', c.chapter_name
            ) ORDER BY c.chapter_index)
            FROM chapters c
            WHERE c.manga_id = m.id
        ),
        '[]'
    ) AS chapters,

    COALESCE(
        (
            SELECT json_agg(jsonb_build_object(
                'id', g.id,
                'genre', g.genre,
                'created_at', g.created_at
            ))
            FROM manga_genres mg
            JOIN genres g ON g.id = mg.genre_id
            WHERE mg.manga_id = m.id
        ),
        '[]'
    ) AS genres,

    COALESCE(
        (
            SELECT json_agg(jsonb_build_object(
                'author_id', a.id,
                'author_name', a.name,
                'role', ma.role
            ))
            FROM manga_authors ma
            JOIN authors a ON a.id = ma.author_id
            WHERE ma.manga_id = m.id
        ),
        '[]'
    ) AS authors

FROM mangas m;

CREATE UNIQUE INDEX IF NOT EXISTS idx_manga_page_view_manga_id ON manga_page_view (id);

------------------------------------------------
--               [TRIGGERS/FUNCTIONS]         --
------------------------------------------------


CREATE OR REPLACE FUNCTION perform_refresh_manga_page_view()
RETURNS void AS $$
BEGIN
    REFRESH MATERIALIZED VIEW CONCURRENTLY manga_page_view;
END;
$$ LANGUAGE plpgsql;


CREATE OR REPLACE FUNCTION create_user_login_attempt()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO user_login_attempts (user_id)
    VALUES (NEW.id);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;


CREATE OR REPLACE TRIGGER trg_create_user_login_attempt
AFTER INSERT ON users
FOR EACH ROW
EXECUTE FUNCTION create_user_login_attempt();


-- Função que cria o registro na tabela de métricas
CREATE OR REPLACE FUNCTION create_manga_metrics()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO manga_metrics (manga_id)
    VALUES (NEW.id);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger que executa a função após inserir um novo manga
CREATE OR REPLACE TRIGGER trg_create_manga_metrics
AFTER INSERT ON mangas
FOR EACH ROW
EXECUTE FUNCTION create_manga_metrics();


------------------------------------------------
--                 [INDEXES]                  --
------------------------------------------------

-- USERS
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);
CREATE INDEX IF NOT EXISTS idx_users_last_login ON users(last_login_at DESC);

-- USERS SESSIONS
CREATE INDEX IF NOT EXISTS idx_user_session_tokens_user ON user_session_tokens(user_id) WHERE revoked = FALSE;
CREATE INDEX IF NOT EXISTS idx_user_session_tokens_expires ON user_session_tokens(expires_at) WHERE revoked = FALSE;
CREATE INDEX IF NOT EXISTS idx_login_attempts_locked ON user_login_attempts(locked_until) WHERE locked_until IS NOT NULL;

-- MANGAS
CREATE INDEX IF NOT EXISTS idx_mangas_title ON mangas(title);
CREATE INDEX IF NOT EXISTS idx_mangas_status ON mangas(status);
CREATE INDEX IF NOT EXISTS idx_mangas_created_at ON mangas(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_mangas_updated_at ON mangas(updated_at DESC);

-- MANGA_ALT_TITLES
CREATE INDEX IF NOT EXISTS idx_manga_alt_titles_manga_id ON manga_alt_titles(manga_id);
CREATE INDEX IF NOT EXISTS idx_manga_alt_titles_title ON manga_alt_titles(title);

-- AUTHORS
CREATE INDEX IF NOT EXISTS idx_authors_name ON authors(name);

-- AUTHOR_ROLES
CREATE INDEX IF NOT EXISTS idx_author_roles_manga_id ON author_roles(manga_id);
CREATE INDEX IF NOT EXISTS idx_author_roles_author_id ON author_roles(author_id);

-- LOGS
CREATE INDEX IF NOT EXISTS idx_logs_created_at ON logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_logs_level ON logs(level, created_at DESC);

-- GENRES
CREATE INDEX IF NOT EXISTS idx_genres_genre ON genres(genre);

-- MANGA_GENRES
CREATE INDEX IF NOT EXISTS idx_manga_genres_manga_id ON manga_genres(manga_id);
CREATE INDEX IF NOT EXISTS idx_manga_genres_genre_id ON manga_genres(genre_id);

-- CHAPTERS
CREATE INDEX IF NOT EXISTS idx_chapters_manga_id ON chapters(manga_id);
CREATE INDEX IF NOT EXISTS idx_chapters_manga_chapter ON chapters(manga_id, chapter_index);
CREATE INDEX IF NOT EXISTS idx_chapters_created_at ON chapters(created_at DESC);

-- CHAPTER_IMAGES (aplicado em cada partição)
CREATE INDEX IF NOT EXISTS idx_chapter_images_chapter_id_p0 ON chapter_images_p0(chapter_id);
CREATE INDEX IF NOT EXISTS idx_chapter_images_chapter_idx_p0 ON chapter_images_p0(chapter_id, image_index);

CREATE INDEX IF NOT EXISTS idx_chapter_images_chapter_id_p1 ON chapter_images_p1(chapter_id);
CREATE INDEX IF NOT EXISTS idx_chapter_images_chapter_idx_p1 ON chapter_images_p1(chapter_id, image_index);

CREATE INDEX IF NOT EXISTS idx_chapter_images_chapter_id_p2 ON chapter_images_p2(chapter_id);
CREATE INDEX IF NOT EXISTS idx_chapter_images_chapter_idx_p2 ON chapter_images_p2(chapter_id, image_index);

CREATE INDEX IF NOT EXISTS idx_chapter_images_chapter_id_p3 ON chapter_images_p3(chapter_id);
CREATE INDEX IF NOT EXISTS idx_chapter_images_chapter_idx_p3 ON chapter_images_p3(chapter_id, image_index);

CREATE INDEX IF NOT EXISTS idx_chapter_images_chapter_id_p4 ON chapter_images_p4(chapter_id);
CREATE INDEX IF NOT EXISTS idx_chapter_images_chapter_idx_p4 ON chapter_images_p4(chapter_id, image_index);

CREATE INDEX IF NOT EXISTS idx_chapter_images_chapter_id_p5 ON chapter_images_p5(chapter_id);
CREATE INDEX IF NOT EXISTS idx_chapter_images_chapter_idx_p5 ON chapter_images_p5(chapter_id, image_index);

CREATE INDEX IF NOT EXISTS idx_chapter_images_chapter_id_p6 ON chapter_images_p6(chapter_id);
CREATE INDEX IF NOT EXISTS idx_chapter_images_chapter_idx_p6 ON chapter_images_p6(chapter_id, image_index);

CREATE INDEX IF NOT EXISTS idx_chapter_images_chapter_id_p7 ON chapter_images_p7(chapter_id);
CREATE INDEX IF NOT EXISTS idx_chapter_images_chapter_idx_p7 ON chapter_images_p7(chapter_id, image_index);

CREATE INDEX IF NOT EXISTS idx_chapter_images_chapter_id_p8 ON chapter_images_p8(chapter_id);
CREATE INDEX IF NOT EXISTS idx_chapter_images_chapter_idx_p8 ON chapter_images_p8(chapter_id, image_index);

CREATE INDEX IF NOT EXISTS idx_chapter_images_chapter_id_p9 ON chapter_images_p9(chapter_id);
CREATE INDEX IF NOT EXISTS idx_chapter_images_chapter_idx_p9 ON chapter_images_p9(chapter_id, image_index);

-- LIBRARY
CREATE INDEX IF NOT EXISTS idx_library_user_id ON library(user_id);
CREATE INDEX IF NOT EXISTS idx_library_manga_id ON library(manga_id);
CREATE INDEX IF NOT EXISTS idx_library_status ON library(reading_status);
CREATE INDEX IF NOT EXISTS idx_library_user_manga ON library(user_id, manga_id);
CREATE INDEX IF NOT EXISTS idx_library_updated ON library(updated_at DESC) WHERE updated_at IS NOT NULL;

-- COLLECTIONS
CREATE INDEX IF NOT EXISTS idx_collections_created_at ON collections(created_at DESC);

-- COLLECTIONS_MANGAS
CREATE INDEX IF NOT EXISTS idx_collections_mangas_manga_id ON collections_mangas(manga_id);
CREATE INDEX IF NOT EXISTS idx_collections_mangas_collection_id ON collections_mangas(collection_id);

-- BUG_REPORTS
CREATE INDEX IF NOT EXISTS idx_bug_reports_type ON bug_reports(bug_type);
CREATE INDEX IF NOT EXISTS idx_bug_reports_created_at ON bug_reports(created_at DESC);

-- MANGA_REQUESTS
CREATE INDEX IF NOT EXISTS idx_manga_requests_created_at ON manga_requests(created_at DESC);


-- MANGA_METRICS
CREATE INDEX IF NOT EXISTS idx_manga_metrics_total_reads ON manga_metrics(total_reads DESC);

-- GLOBAL_METRICS
CREATE INDEX IF NOT EXISTS idx_global_metrics_date ON global_metrics(metric_date DESC);

-- USER_EVENTS (CRÍTICO para performance dos triggers)
CREATE INDEX IF NOT EXISTS idx_user_events_user_id ON user_events(user_id);
CREATE INDEX IF NOT EXISTS idx_user_events_entity ON user_events(entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_user_events_type ON user_events(event_type);
CREATE INDEX IF NOT EXISTS idx_user_events_created_at ON user_events(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_user_events_user_created ON user_events(user_id, created_at DESC);

-- Índices compostos para queries comuns
CREATE INDEX IF NOT EXISTS idx_user_events_chapter_read 
ON user_events(entity_id, created_at DESC) 
WHERE event_type = 'chapter_read' AND entity_type = 'chapter';

CREATE INDEX IF NOT EXISTS idx_user_events_manga_opened 
ON user_events(entity_id, created_at DESC) 
WHERE event_type = 'manga_opened' AND entity_type = 'manga';

-- Índice GIN para busca em metadata JSONB
CREATE INDEX IF NOT EXISTS idx_user_events_metadata ON user_events USING GIN(metadata);

-- APP_INFOS
CREATE INDEX IF NOT EXISTS idx_app_infos_name ON app_infos(name);


------------------------------------------------
--           [ÍNDICES FULL-TEXT SEARCH]       --
------------------------------------------------

-- Para busca eficiente de mangás por título e descrição
CREATE INDEX IF NOT EXISTS idx_mangas_title_trgm ON mangas USING gin(title gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_mangas_descr_trgm ON mangas USING gin(descr gin_trgm_ops);

-- Para busca de autores
CREATE INDEX IF NOT EXISTS idx_authors_name_trgm ON authors USING gin(name gin_trgm_ops);



SELECT perform_refresh_manga_page_view();